### PR TITLE
The-Next-Web-Clone Project

### PR DESCRIPTION
**Pull request by Laguna1**
This assignment consists of making a responsive web page from the site The Next Web (https://thenextweb.com/). The page was built using a combination of CSS grids, CSS flexbox.
The clone was made with the following breakpoints.
The screen sizes used were the default responsive screen sizes as taken from the Google Chrome Developer Browser.
Mobile S 320 X 708 (Portrait Mode) Tablet 768 X 708 (Portrait Mode) Laptop 1440 X 708 (Portrait Mode)
Please, check our code.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback

**Comment by nikasulo** [comment]
# Great work! @Laguna1 and @Romel4321 :clap: 
Your project is really great, you have put in a lot of work and it shows! Please consider my comments below towards bringing this all together, make the necessary changes and request another review! I wish you all the best and see you at the very top :rocket: 

#### Responsiveness
Your project could use a little more responsiveness, please look a little more closely at the sizes of elements, padding of sections, margins, and general element positionings. These are very key as they will affect the look, feel, and more importantly the usability of your sites. I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out.

#### Navigation bar
Your navigation bar is a little buggy, the positioning of elements, and padding of the navigation are in a little twist. Consider comparing what the original site looks like(including but not limited to responsiveness) to yours and make any appropriate changes. 

* Original
screeenshot
* Yours
screeenshot
* Original
screeenshot
* Yours
screeenshot
* Original
screeenshot
* Yours
screeenshot

Please note that while there are still more issues with your responsiveness, I have only highlighted the navigation bar, please take a second look at ALL sections on the 3 major screen sizes and make sure they match closely with the original! I wish you the best :handshake: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Comment by nikasulo** [comment]
# Nice work team! @Laguna1 and @Romel4321 :+1: 
I see you tried to incorporate the changes I proposed in the last review, however, the issues with your navigation bar still persist. Furthermore, I think you may not have considered the other sections in your project closely as there are still a lot of disparities between your project and the original site. Please take a look at some screenshots below in an attempt to bring a few to your notice, however, please look through the ENTIRE project for these differences.

* Original
screenshot
* Yours
screenshot

* Original
screenshot
* Yours
screenshot

### Summary
Please do your best to compare your project to the original on the following screen sizes: 320px, 768px, 1024px, using the dev tools in your browser. Try to get your page looking as close to the original as possible. I wish you the very best and see you at the top

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by Laguna1** [comment]
Our The Next Web clone was made with the following breakpoints.
The screen sizes used were the default responsive screen sizes as taken from the Google Chrome Developer Browser.
Mobile S 320 X 708 (Portrait Mode) Tablet 768 X 708 (Portrait Mode) Laptop 1440 X 708 (Portrait Mode).
We made corrections based on your comments. Please, indicate all possible comments on this project in one review.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi **Team**, you did a great job implementing the changes pointed out by the previous reviewer 👍 , However, we need to work a little bit with this project before we can proceed. Find the comments below:
* ```In mobile screen``` the 3 articles should be arranged in rows. Currently, this is how it looks
lp1
```Original version```
lp2
* Currently, the latest news section does not look good on mobile devices. This is how it looks so we compare with the original
lp3
```Original version```
lp4
* Currently, the latest funding does not look good. Let us check our version and compare with the original
lp5
```Original version```
lp6
* Let us fix this part. Currently, we have 2 columns but we should have 1 column like the original
lp7
```Original version```
lp8
* Currently, the latest deals section does not look good. Each article should span 1 column, but we have 3 columns. 
This is our version
lp9
```Original version```
lp99
* Kindly compare our version to the original in medium screen sizes

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
Find me on slack on Daniel Larbi Addo

**Comment by Laguna1** [comment]
Please look again.
Our clone has three versions,
for the screen 1440px, 768px and 320px respectively.
And the layout of the elements corresponds to the original page.
kindly recommended checking our project In your environment in tablet version cause it`s exactly as in the original.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🎈 

Hi **Team**, we realize you did not make any changes based on the previous review. 👍 However, the project is not responsive to my device. As a developer, we try to fix problems as we create programs.
Kindly consider working on the responsiveness. Thank you 🙂 

 Good luck with your next submission 👍 
_Happy coding_
Daniel Larbi Addo

**Comment by addod19** [comment]
> Please look again.
> Our clone has three versions,
> for the screen 1440px, 768px and 320px respectively.
> And the layout of the elements corresponds to the original page.
> kindly recommended checking our project In your environment in tablet version cause it`s exactly as in the original.

Hi Team, there is still responsiveness to fix as indicated earlier. Kindly take a screenshot of the types of screens working on your device so we can understand the problem. Thank you 😃

**Comment by Laguna1** [comment]
Ok where to send these screenshots?


чт, 12 мар. 2020 г. в 00:36, Daniel Larbi Addo <notifications@github.com>:

**Comment by Laguna1** [comment]
чт, 12 мар. 2020 г. в 00:38, Laguna Zootovary <lagunazoomarket@gmail.com>:

**Comment by Laguna1** [comment]
чт, 12 мар. 2020 г. в 00:45, Laguna Zootovary <lagunazoomarket@gmail.com>:

**Comment by Laguna1** [comment]
чт, 12 мар. 2020 г. в 00:46, Laguna Zootovary <lagunazoomarket@gmail.com>:

**Comment by addod19** [comment]
You can send the screenshot at the same place you send the text

**Comment by Laguna1** [comment]
Ok, how I can add screenshots here?

**Comment by addod19** [comment]
Drag the image to the text area

**Comment by Laguna1** [comment]
screen320
screen768
screen1440

**Comment by Laguna1** [comment]
We made this project for three sizes of devices - for the screen 1440px, 768px and 320px,
accordingly we think that all elements of the page of our project behave in the same way as the same elements on the original page when the browser is resized. Our breakpoints - 1440px - 768px - 320px.

**Comment by thsvr** [comment]
**STATUS: APPROVED** :1st_place_medal: :1st_place_medal: 

Hi @Laguna1 and @Romel4321 :smile: :smile:

Congratulations :1st_place_medal: for the hard work :fireworks: :fireworks:  


Can you please update the live version before merge your project to master?

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project**  :computer_mouse: :desktop_computer: 

_Thaís Vieira (TSE)_

**Pull request merged**
